eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8070
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: springstudent
    password: springstudent
  application:
    name: schools
  config:
    import: optional:configserver:http://localhost:8888
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
application:
  config:
    students-url: http://localhost:8090/api/v1/students