eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: springstudent
    password: springstudent
  application:
    name: students
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
